project:
  type: website
  output-dir: "docs"

website:
  title: "Sreeparna Vappala"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Teaching"
        href: "teaching/index_teach.qmd"
      - text: "CV"
        file: CV.qmd
      - text: "Contact"
        file: contact.qmd
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

